version: '2.1'
services:

  doris-fe:
    image: yiluxiangbei/doris-init:0.14.0-611
    container_name: doris-fe
    ports:
      - 8030:8030
      - 9010:9010
      - 9020:9020
      - 9030:9030
    environment:
      - DORIS_ROLE=fe-leader
    volumes:
      - ./doris/fe/doris-meta:/opt/doris/fe/doris-meta
      - ./doris/fe/log:/opt/doris/fe/log
      - ./doris/conf/fe.conf:/opt/doris/fe/conf/fe.conf
    networks:
      tortoise-network :
        ipv4_address: 172.20.0.198
    restart: always

  doris-be:
    image: yiluxiangbei/doris-init:0.14.0-611
    container_name: doris-be
    environment:
      - DORIS_ROLE=be
    ports:
      - "8040:8040"
      - "8060:8060"
      - "9050:9050"
      - "9060:9060"
      - "9070:9070"
    volumes:
      - ./doris/be/storage:/opt/doris/be/storage
      - ./doris/be/log:/opt/doris/be/log
      - ./doris/conf/be.conf:/opt/doris/be/conf/be.conf
    networks:
      tortoise-network :
        ipv4_address: 172.20.0.199
    restart: always

  kettle:
    image: yiluxiangbei/tortoise-kettle:8.3
    container_name: kettle
    ports:
      - 8010:9051
      - 8011:18080
    volumes:
      - ./doris/conf/:/opt/tortoise/conf
      - ./tortoise/kettle-data:/opt/tortoise/data/kettle
    networks:
      - tortoise-network
    restart: always

networks:
  tortoise-network:
    external: true