version: '2.1'
services:

  doris-fe:
    image: registry.cn-qingdao.aliyuncs.com/dataease/doris-init:0.14.0-611
    container_name: doris-fe
    environment:
      - DORIS_ROLE=fe-leader
    volumes:
      - dataease-fe-data:/opt/doris/fe/doris-meta
      - dataease-fe-logs:/opt/doris/fe/log
      - /opt/dataease/conf/fe.conf:/opt/doris/fe/conf/fe.conf
    networks:
      dataease-network :
        ipv4_address: 172.19.0.198
    restart: always

  doris-be:
    image: registry.cn-qingdao.aliyuncs.com/dataease/doris-init:0.14.0-611
    container_name: doris-be
    environment:
      - DORIS_ROLE=be
    volumes:
      - dataease-be-data:/opt/doris/be/storage
      - dataease-be-logs:/opt/doris/be/log
      - /opt/dataease/conf/be.conf:/opt/doris/be/conf/be.conf
    networks:
      dataease-network :
        ipv4_address: 172.19.0.199
    restart: always

  kettle:
    image: registry.cn-qingdao.aliyuncs.com/dataease/kettle:8.3
    container_name: kettle
    volumes:
      - /opt/dataease/conf/:/opt/dataease/conf
      - dataease-kettle-data:/opt/dataease/data/kettle
    networks:
      - dataease-network
    restart: always

volumes:
  dataease-fe-data:
    driver_opts:
      type: none
      device: /opt/dataease/data/fe
      o: bind
  dataease-be-data:
    driver_opts:
      type: none
      device: /opt/dataease/data/be
      o: bind
  dataease-be-logs:
    driver_opts:
      type: none
      device: /opt/dataease/logs/be
      o: bind
  dataease-fe-logs:
    driver_opts:
      type: none
      device: /opt/dataease/logs/fe
      o: bind