version: '3.7'
services:
  doris-be:
    image: doris:0.12.21-release
    restart: always
    network_mode: "host"
    container_name: "doris-be"
    ports:
      - "8040:8040"
      - "8060:8060"
      - "9050:9050"
      - "9060:9060"
      - "9070:9070"
    volumes:
      - "/xxx/doris/be/log:/home/doris/be/log"
      - "/xxx/doris/be/storage:/home/doris/be/storage"
      - "/xxx/doris/be/conf:/home/doris/be/conf/"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - FE_ROLE=be